"facebook tutorial link"="https://www.youtube.com/watch?v=VADy1X8NHeo"
"firebase firestore link"="https://console.firebase.google.com/project/project1-b3594/firestore/databases/-default-/data/~2Fchats~2F7asGpjmbZiUpTozfrQVU"
"facebook app link"="https://developers.facebook.com/apps/533618776122926/settings/basic/"
"base64 converter link" = "https://base64.guru/converter/encode/hex"
"build expo app link"="https://expo.dev/accounts/rezgui.imen/projects/tutorialApp/builds/2ce6ba7d-e7d1-4469-bc4d-344fdf309c39"
"commande to run app"="npm start --dev-client"